apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: three-tier
data:
  MONGO_HOST: "mongodb-service"
  MONGO_PORT: "27017"
  MONGO_DB: "appdb"
  NODE_ENV: "production"
  PORT: "3000"
