apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: three-tier
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9hcHBkYg==
